manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.2.0
      import: true

    - name: usp
      path: modules/lib/usp
      url: https://github.com/Lora-net/usp.git
      revision: main
      submodules: true

    - name: usp_zephyr
      path: modules/lib/usp_zephyr
      url: https://github.com/Lora-net/usp_zephyr.git
      revision: main

  self:
    path: application
